### ISSUE TITLE
router integration

### ISSUE THREAD

**Issue by burningTyger** [MisRob/vue-tree-navigation#1]
Is there a way to integrate router functionality? Instead of using plain old `a` tags?
Otherwise a very promising library.

**Comment by MisRob** [comment]
Hi, I am going to add `vue-router` support in the next release as I need it too :) I would like to keep both options in the future so people can choose which one they need (I've got few projects where I don't need a router functionality too). Yet I'm not sure about the interface - I guess I could just add a new simple property `router: true/false`?

**Comment by The-BlackWidow** [comment]
@MisRob Do you need help? We also need to use the `vue-rooter` and are willing to do it this week if you want!

**Comment by MisRob** [comment]
@The-BlackWidow Hi, thank you! :) I already implemented the feature and I've got it running locally. Tomorrow I am going to test it in my projects and then I am going to release `1.1.0` (tomorrow or after-tomorrow). But in general, contributors are very welcome so please feel free to create a PR any time ;) !

**Comment by The-BlackWidow** [comment]
@MisRob Perfect timing for us! Thank you very much

**Comment by MisRob** [comment]
@The-BlackWidow Hello, if you have some time, you can help me to try the new version (branch `router-support`) :) I already used it in three projects and it seems ok but it would be be good if someone else looked at it before the official release. The only thing missing is a new demo page.

If you decide to play with it, please study the new README carefully. I changed input data format (`href` -> `element`, new field `route`) because I decided to do it more dynamic (I didn't wish to restrict someone to use navigation based on routes only or element IDs only) and let users combine routes with element IDs. This means, the next version is going to be `2.0.0` :)

You can run the development server with some data prepared or install the new version to one of your projects with `npm install git://github.com/MisRob/vue-tree-navigation.git#router-support`

**Comment by The-BlackWidow** [comment]
@MisRob good! I'll update my package.json with the git version and I'll keep you posted! Maybe I will give you feedbacks on Monday (or on Tuesday depending on your timezone ^^ (mine is UTC+1:00))

**Comment by MisRob** [comment]
@The-BlackWidow Sure, no need to hurry, I am going to wait and prepare a demo meanwhile probably :) Also I am a little bit ill so I am going to take it slowly ;) Thanks and have a nice weekend!

**Comment by MisRob** [comment]
I decided to build the documentation page and use it as the demo project at the same time. It's not finished yet but all the content is there already and router is working. Preview lives here https://pensive-nightingale-f5d96b.netlify.com

**Comment by MisRob** [comment]
Demo/doc done

**Comment by MisRob** [comment]
Demo/doc done. I removed the documentation from vue-tree-navigation README, please have a look at preview webpage for detailed documentation.

**Comment by MisRob** [comment]
Demo/doc done. I removed the documentation from vue-tree-navigation README, please have a look at the preview webpage for detailed documentation.

**Comment by MisRob** [comment]
Release notes prepared. I guess I am done with it for now :) I am going to wait till tomorrow (to see if @The-BlackWidow or anyone else who want to try it didn't have any troubles with the new version) and release it in the afternoon if everything is ok.

**Comment by MisRob** [comment]
Release notes prepared. I guess I am done with it for now :) I am going to wait till tomorrow (to see if @The-BlackWidow or anyone else who want to try it doesn't have any essential troubles with the new version) and release it in the afternoon if everything is ok. Smaller issues will be resolved over time. I would like to merge this as soon as possible as I won't have much time for this next week.

**Comment by MisRob** [comment]
Release notes prepared. I guess I am done with it for now :) I am going to wait till tomorrow (to see if @The-BlackWidow or anyone else who want to try it doesn't have any essential troubles with the new version) and release it in the afternoon if everything is ok. Smaller issues will be resolved over time as new minor versions. I would like to merge it and release 2.0.0 as soon as possible as I won't have much time for this next week.

**Comment by MisRob** [comment]
Release notes prepared. I guess I am done with it for now :) I am going to wait till tomorrow (to see if @The-BlackWidow or anyone else who want to try it doesn't have any essential troubles with the new version) and release it in the afternoon if everything is ok. Smaller issues will be resolved over time in next minor versions. I would like to merge it and release 2.0.0 as soon as possible as I won't have much time for this next week.

**Comment by MisRob** [comment]
Release notes prepared. I guess I am done with it for now :) I am going to wait till tomorrow (to see if @The-BlackWidow or anyone else who want to try it doesn't have any essential troubles with the new version) and release it in the afternoon if everything is ok. Smaller issues will be resolved over time in next minor versions. I would like to merge it and release 2.0.0 as soon as possible as I won't have much time for this next week.

**Comment by The-BlackWidow** [comment]
Hello @MisRob !
Thank you so much for all the good work!
So I've just presented the tree within our interface, and here are the notes I was given: 
- Is it possible to open a node by clicking on the text rather than on the ">" icon only?
- Is it possible to customize the ">" icon into another icon?
Everything works perfectly for us!

**Comment by MisRob** [comment]
Cool, thank you :)

I am glad everything is working and that you found time to check it before the release so thank you, too :)

About the notes:

> Is it possible to open a node by clicking on the text rather than on the ">" icon only?
No, this is not possible right now, but it would be nice (especially on mobile devices). I am going to add this to feature requests (I've got more of them and I am going to write them all to issues after v2.0.0 release)

> Is it possible to customize the ">" icon into another icon?
I didn't try this so far but I guess you could override css for navigation toggle component which looks like this:

```
.navigation-toggle {
  position: relative;
  top:      -3px;
  padding:  6px;
  cursor:   pointer;

  .navigation-toggle-icon {
    display:      inline-block;
    padding:      3px;
    border:       solid #000;
    border-width: 0 2px 2px 0;
    transform:    rotate(45deg);
  }

  &.closed {
    .navigation-toggle-icon {
      transform: rotate(-45deg);
    }
  }
}
```

It would be nice to try it and document it if everything is ok. I am going to add this to feature requests too ;)

**Comment by MisRob** [comment]
I am going to close this for now and move notes to feature requests later.
