### ISSUE TITLE
native js usage (like jquery cdn)

### ISSUE THREAD

**Issue by Diaskhan** [MisRob/vue-tree-navigation#11]
It is possible to use a native browser installation ?
Via simple browser include ? 

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

**Comment by MisRob** [comment]
Hello, I think it should be possible as I bundled it as UMD to `dist/index.js`. But I actually didn't try. I have been quite busy recently but it's going to be better so I would like to to work on more issues here in upcoming days. I'll try to check it, fix possible issues if there are any and add it to the doc.

**Comment by MisRob** [comment]
Hi, some additional steps were needed. I just published a new version - please see README. Documentation webpage will be updated later.

**Comment by MisRob** [comment]
https://github.com/MisRob/vue-tree-navigation/pull/14
