### ISSUE TITLE
Question: Expand a group when url is typed on the browsers url

### ISSUE THREAD

**Issue by mrin9** [MisRob/vue-tree-navigation#2]
First of, this one is excellent tree-nav , you have kept it to minimal and added only the absolute functionality needed. I was making one for myself as i didn't find any good ones, but yours is excellent. 

One use case, that I am after is,  lets say, there is a ```route```  under a group which is not expanded. Now upon typing this link on the browser's  url, will the corresponding group containing the ```route``` get expanded ?
I just looked at documentation, did not played with it, if its a easy question for you can you tell me the current behavior?

**Comment by MisRob** [comment]
Hi, thank you! I am glad you had a look at the new version and you find it helpful.

About the feature - there's nothing like that so far. Anyway, this behaviour is very desirable. I was already thinking about something like that. I find it quite natural as it would be a little bit weird if someone visited an URL and the corresponding group would stay closed - and I believe the navigation component should be responsible for it. I think this shouldn't be difficult to implement.

Tomorrow I am going to release v2.0.0 and then I am going to add some feature requests to issues (I've got more of them). This one is going to be there too ;) We will see if someone helps me (feel free to join me if you need it quickly) or if I will implement this myself over time.

**Comment by MisRob** [comment]
I am going to close this for now and move it to feature requests later.
