### ISSUE TITLE
Component Registration Issue

### ISSUE THREAD

**Issue by JasonGrant** [MisRob/vue-tree-navigation#27]
I followed the installation instructions and used the sample content provided. Is there something I am missing? I have not had this issue with any other components.
There are no build errors but the console reads:
[Vue warn]: Unknown custom element: <v-tree-navigation> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

This is what I have in my package.json for versions.
"dependencies": {
    "axios": "^0.18.0",
    "gsap": "^2.0.1",
    "lodash": "^4.17.10",
    "vee-validate": "^2.1.0-beta.1",
    "vue": "^2.5.16",
    "vue-content-loading": "^1.5.0",
    "vue-router": "^3.0.1",
    "vuetify": "v1.0.19",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-add-filehash": "^6.9.8",
    "babel-plugin-transform-imports": "^1.5.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-plugin-vue": "^4.5.0",
    "file-loader": "^1.1.11",
    "mdi": "^2.2.43",
    "n": "^2.1.11",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "url-loader": "^1.0.1",
    "vue-loader": "^14.2.2",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "vue-tree-navigation": "^3.0.0",
    "vuex-undo-redo": "^1.0.5",
    "webpack": "^4.11.1",
    "webpack-cli": "^3.0.3",
    "webpack-dev-server": "^3.1.4"
  }

**Comment by MisRob** [comment]
Hi,

I checked setup once again for both installation via npm and installation via script but wasn't able to replicate your problem. This usually happens when you forgot to call `Vue.use` when registering the component.

Not sure what could be wrong. If you are sure it is registered correctly and the problem still persists, could you please share some example repository?

**Comment by MisRob** [comment]
I suppose problem does not persist. Closing.
