### ISSUE TITLE
It should be possible to open a group by clicking on the text

### ISSUE THREAD

**Issue by MisRob** [MisRob/vue-tree-navigation#9]
Now you need to click on the ">" icon. This is not very suitable for mobile devices where the icon is small.
The group should open and the user should be redirected to the location at the same time. This should be a default behaviour. I'm not sure if this should be the only option available or whether people should have a possibility to change the behaviour.

**Comment by MisRob** [comment]
Desired behaviour:

Closed group
- when text clicked => open group
- when toggle clicked => open group

Opened group
- when text clicked => let the group opened
- when toggle clicked => close the group

**Comment by MisRob** [comment]
prepared in dev, will be released in 3.0.0

**Comment by patie** [comment]
@MisRob is this now possible?

**Comment by MisRob** [comment]
@patie Hi
When a group is already opened and a user clicks its parent text it would not be very intuitive to close the group because obviously, the user needs to visit the group again (so he would need to click it three times actually if he was already there and needed to visit some of the group child links again).

From the technical point of view, it can be configurable, it's nothing hard to implement indeed :) So I am not against opening an issue for this. But before doing so, I would like to see some use case when this behavior is desirable, do you have an example? Thank you.
